#!/bin/bash

## $IMAGE_NAME is injected by Hub
#export RW_BLDHASH=$(date | sha256sum | awk '{print $1}')
#export RW_VCSHASH=$(git rev-parse HEAD)
#export LS_VCSREF=$(git rev-parse --short HEAD)
#export LS_BLDDATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ"

docker build \
	--build-arg RW_BLDHASH=`date | sha256sum | awk '{print $1}'` \
	--build-arg RW_VCSHASH=`git rev-parse HEAD` \
	--build-arg RW_VCSBRANCH=`git rev-parse --abbrev-ref HEAD` \
	--build-arg LS_VCSREF=`git rev-parse --short HEAD` \
	--build-arg LS_BLDDATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
	--build-arg LS_VENDOR="RootWyrm.com"
	--build-arg LS_SCHEMA=`grep LS_SCHEMA build.conf | cut -d = -f 2` \
	--build-arg LS_SCHEMAVERSION=`grep LS_SCHEMAVERSION build.conf | cut -d = -f 2` \
	--build-arg LS_NAME=`grep LS_NAME build.conf | cut -d = -f 2` \
	--build-arg LS_URL=`grep LS_URL build.conf | cut -d = -f 2` \
	-t $IMAGE_NAME .
	
## NYI
#	--build-arg LS_VERSION=`./get_version.sh` \
